### ISSUE TITLE
Logrotate doesn't work in a docker image

### ISSUE THREAD

**Issue by cprivitere** [pureelk/pureelk#10]
The logrotate solution put into the pureelk image relies on cron. Cron doesn't run right in an ubuntu docker image. See here for more info: http://phusion.github.io/baseimage-docker/

Long story short, upstart doesn't work and cron requires upstart.

We need another solution for the logrotate stuff as these log files still get gigantic and fill the disk after a month of running.

**Comment by cprivitere** [comment]
Glad to see the update for the kibana version and the docker level logging. Hoping to get some acknowledgement of this issue eventually....

**Comment by cprivitere** [comment]
Still looking for an acknowledgement of this issue...

**Comment by gary-yang** [comment]
Sorry for the delay. This issue is now fixed. We are now setting the maximum log size in the container. Thanks for reporting this!

**Comment by cprivitere** [comment]
No the change you guys added only adjusts the docker log size, not the array-tasks.log file.

**Comment by cprivitere** [comment]
So to be clear, I'm referring to these files:
/var/log/pureelk/array-tasks.log
/var/log/pureelk/scheduler.log

Sorry if that wasn't clear.

Those files get to many many GB in size in just a week or two.

**Comment by gary-yang** [comment]
Actually you are right. We only set max-size. Per Docker documentation, we should also include max-file.

**Comment by cprivitere** [comment]
The log driver stuff doesn't affect all files being written by your container. That's only for docker logging. You'll need another solution to deal with these files than the options you're referring to here.

**Comment by gary-yang** [comment]
We merged in a change that adds logrotate to the log files.
